version: '3.8'

services:
  db:
    image: xploiterd/expression_db
    container_name: expression_db
    restart: always
    environment:
      POSTGRES_DB: expression
      POSTGRES_USER: rounakadmin
      POSTGRES_PASSWORD: rounakadmin
    ports:
      - "5432:5432"

  app:
    image: xploiterd/expression
    container_name: expression_app
    restart: always
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: rounakadmin
      DATABASE_PASSWORD: rounakadmin
      DATABASE_NAME: expression
